import employeeRepository from '../repositories/employeeRepository';

class EmployeeController {

    async saveEmployee(req, res) {
        try {
            let employee = {};
            // Get values from request body
            employee.first_name= req.body.firstName;
            employee.middle_name= req.body.middleName;
            employee.last_name= req.body.lastName;
            employee.dob= req.body.dob;
            employee.address= req.body.address;
            employee.contact_no= req.body.contactNo;
            employee.gender= req.body.gender;
            employee.email= req.body.email;
            employee.status = 'disabled';

            // Generate employee ID
            //TODO: call the helper and generate employee id
            employee.employeeNo = 'autogenerated';

            //TODO: upload image and set image path

            let newEmployee = await employeeRepository.create(employee);

            res.status(200).send({
                'success': true,
                'data': newEmployee,
                'msg': "Successfully Saved"
            });
        } catch (e) {
            res.status(200).send({
                'success': false,
                'msg': e.message
            });
        }
    }

    async getAllEmployees(req, res) {
        try {
            let employees = await employeeRepository.findAll();
            res.status(200).send({
                'success': true,
                'data': employees
            });
        } catch (e) {
            res.status(200).send({
                'success': false,
                'msg': e.message
            });
        }
    }

    async getEmployeeById(req, res) {
        try {
            let employeeId = req.params.id;
            let employee = await employeeRepository.findById(employeeId);
            res.status(200).send({
                'success': true,
                'data': employee
            });
        } catch (e) {
            res.status(200).send({
                'success': false,
                'msg': e.message
            });
        }
    }

    async updateEmployee(req, res) {
        try {
            let employee = {};

            let employeeId = req.params.id;
            employee.first_name = req.body.firstName;
            employee.middle_name = req.body.middleName;
            employee.last_name = req.body.lastName;
            employee.address = req.body.address;
            employee.gender = req.body.gender;
            employee.contact_no = req.body.contactNo;
            employee.dob = req.body.dob;
            employee.email = req.body.email;

            let isUpdated = await employeeRepository.update(employeeId, employee)

            if (isUpdated) {
                res.status(200).send({
                    'success': true,
                    'msg': "Successfully Updated"
                });
            }
        } catch (e) {
            res.status(200).send({
                'success': false,
                'msg': e.message
            });
        }
    }

    async deleteEmployee(req, res) {
        try {
            const employeeId = req.params.id
            let isDeleted = await employeeRepository.destroy(employeeId)
            if (isDeleted) {
                res.status(200).send({
                    'success': true,
                    'msg': "Successfully Deleted"
                });
            }
        } catch (e) {
            res.status(200).send({
                'success': false,
                'msg': e.message
            });
        }
    }

}

const employeeController = new EmployeeController();
export default employeeController;
